let product = [
  {   
      id: 0,
      name: "Mắt biếc",
      kind: "Blues",
      rot: 33,
      singer: "Bằng Kiều",
      pic: "Mắt Biêc Bằng Kiều.png",
      caretory: "New LP",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      price: 1200000,
      list: [
          "1. Rồi mai tôi đưa em",
          "2. Hạ trắng",
          "3. Dấu tình sầu",
          "4. Phôi pha",
          "5. Mắt biếc",
          "6. Bài không tên số 2",
          "7. Thu hát cho người",
          "8. Lệ đá"
      ]
  },
  {
      id: 1,
      name: "The Best",
      singer: "Bảo Yến",
      kind: "Jazz",
      pic: "Bảo Yến_The best.png",
      rot: 33,
      caretory: "New LP",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      price: 1200000,
      list: [
          "1A. THOI THE THI CHIA TAY",
          "2A. KHUC THUY DU",
          "3A. CHUYEN HOP TAN",
          "4A. TRONG CUOC TINH AN HAN",
          "5A. ANH CON NO EM",
          "1B. CHUYEN BA NGUOI",
          "2B. BIET DEN BAO GIO",
          "3B. CHIEC LA CUOI CUNG",
          "4B. CHIEU HA VANG",
          "5B. COI MONG"
      ]
  },
  {   
      id: 2,
      name: "Giọt Lệ Sầu",
      singer: "Chế Linh",
      kind: "Bolero",
      pic: "Chế Linh.png",
      rot: 33,
      caretory: "New LP",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      price: 1200000,
      list: [
          "1A. GIOT LE SAU",
          "2A. MOT LAN CUOI",
          "3A. TINH PHU",
          "4A. MUOI NAM TINH CU",
          "1B. HAN TINH",
          "2B. TINH CHET THEO MUA DONG",
          "3B. NGHEN NGAO",
          "4B. THANH PHO MUA BAY",
          "5B. LOI CUOI CHO NGUOI TINH PHU"
      ]

  },
  {
      id: 3,
      name: "Đĩa than Chuyện Hẹn Hò",
      singe: "Nhiều ca sĩ",
      pic: "Chuyện Hẹn Hò.png",
      kind: "Bolero",
      rot: 33,
      caretory: "New LP",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      price: 1000000,
      list: [
          "1. Chuyện hẹn hò - Hương Lan & Thái Châu",
          "2. Thu sầu - Thái Châu",
          "3. Sầu lẻ bóng - Hương Lan ",
          "4. Đà lạt hoàng hôn - Thái Châu ",
          "1. Không bao giờ quên anh - Hương Lan ",
          "2. Tà áo cưới - Thái Châu",
          "3. Nỗi buồn hoa phượng - Hương Lan ",
          "4. Đường xưa lối cũ - Hương Lan & Thái Châu"
      ]
  },
  {
      id: 4,
      name: "Đập Vỡ Cây Đàn",
      singer: "Duy khánh",
      pic: "Đập vỡ Cây Đàn.png",
      kind: "383",
      caretory: "New 100%",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      rot: 45,
      price: 1200000,
      list: [
          "1. Đập vỡ cây đàn",
          "2. Lời đắng cho cuộc tình",
          "3. Qua cơn mê",
          "4. Trường cũ tình xưa",
          "5. Thương về miền Trung",
          "6. Những chiều không có em",
          "7. Linh hồn tượng đá",
          "8. Mưa trên phố Huế"
      ]
  },
  {
      id: 5,
      name: "Chuyện ba mùa mưa",
      singer: "Nhiều ca sĩ",
      pic: "5.png",
      kind: "383",
      rot: 78,
      caretory: "New LP",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      price: 800000,
      list: [
          "01. Chuyện ba mùa mưa",
          "02. Kiếp Cầm ca và Thành phố buồn",
          "03. Đắp mộ cuộc tình",
          "04. Con Quỳ Lạy Chúa Trên Trời",
          "05.Phố Đêm",
          "06.CHuyện ba mùa mưa",
          "07. Côi nhớ",
          "08. Nắng Chiều Rực Ro",
          "09. Đường Chiều Lá Rụng",
          "10. Những Gì Đem Theo Vào Cõi Chết",
          "11. Outtro"
      ]
  },
  {
      id: 6,
      name: "Lênh đênh nhớ phố",
      kind: "Bolero",
      pic: "Phố Nhớ.png",
      rot: 78,
      singer: "Giang Trang",
      caretory: "New 100%",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      price: 1000000,
      list: [
          "1.Rừng xưa đã khép (Hoà tấu)",
          "2. Như tiếng thở dài",
          "3. Ru đời đi nhé",
          "4. Vườn xưa",
          "5. Lời thiên thu gọi",
          "6. Đời cho ta thế",
          "7. Tuổi đá buồn",
          "8. Góp lá mùa xuân",
          "9. Mưa hồng",
          "10. Rừng xưa đã khép",
      ]
  },
  {
      id: 7,
      name: "Đĩa than Hoa Trinh Nữ",
      kind: "Bolero",
      pic: "Hoa Trinh nữ.png",
      rot: 78,
      singer: "Nhiều ca sĩ",
      caretory: "New 100%",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      price: 1200000,
      list: [
          "1A. LK Tạ từ trong đêm & Từ đó em buồn",
          "2A. Hàn mặc tử",
          "3A. Chuyện hẹn hò",
          "4A. Khi người yêu tôi khóc & Trên đỉnh mùa đông",
          "1B. Hoa trinh nữ",
          "2B. Yêu người như thế đó",
          "3B. Lâu đài tình ái",
          "4B. Mùa đông của anh",
      ]
  },
  {
      id: 8,
      name: "Thriller",
      kind: "Jazz",
      rot: 45,
      pic: "Thriller.png",
      singer: "Micheal Jason",
      caretory: "Old 90s",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      price: 1200000,
      list: [
          "1. Human nature",
          "2. The Lady in my life",
          "3. Baby be mine",
          "4. Thriller"
      ]
  },
  {
      id: 9,
      name: "Chuyện Của Lam",
      singer: "Lam Anh",
      pic: "Lam.png",
      kind: "Bolero",
      rot: 78,
      caretory: "New 100%",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      price: 1250000,
      list: [
          "1. Chờ thêm 1 đời",
          "2. Còn nguyên vết thương sâu",
          "3. Em của ngày xưa khác rồi",
          "4. Hương ngọc lan",
          "5. Lạc nhau có phải muôn đời",
          "6. Muộn màng",
          "7. Sau tất cả",
          "8. Phố mùa đông",
      ]
  },
  {
      id: 10,
      name: "Riêng một góc trời",
      singer: "Tuấn Ngọc",
      pic: "TN.png",
      kind: "Bolero",
      rot: 45,
      caretory: "New 100%",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      price: 1250000,
      list: [
          "01. Riêng Một Góc Trời",
          "02. Mắt Lệ Cho Người",
          "03. Dưới Giàn Hoa Cũ",
          "04. Mùa Xuân Sao Chưa Về Hỡi Em",
          "05. Nỗi Đau Muộn Màng",
          "06. Như Đã Dấu Yêu",
          "07. Tâm Sự Gửi Về Đâu",
          "08. Về Đây Nghe Em",
      ]
  },
  {
      id: 11,
      name: "Đêm tâm sự",
      kind: "Bolero",
      pic: "Đêm Tâm Sự_Lệ Quyên.png",
      singer: "Lệ Quyên",
      rot: 33,
      caretory: "New 100%",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      price: 1000000,
      list: [
          "01. Hoa nở về đêm",
          "02. Đêm tâm sự (hát với Thái Châu)",
          "03. Chuyến tàu hoàng hôn",
          "04. Sương lạnh chiều đông",
          "05. Chiều cuối tuần",
          "06. Ai cho tôi tình yêu",
          "07. Câu chuyện đầu năm",
          "08. Người đi ngoài phô",
          "09. Tình yêu trả lại trăng sao",
          "10. Cho vừa lòng em",
      ]
  },
  {
      id: 12,
      name: "Đêm Hẹn hò",
      pic: "Đêm Tâm Sự_Lệ Quyên.png",
      kind: "Bolero",
      singer: "Lệ Quyên",
      rot: 78,
      caretory: "New 100%",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      price: 1050000,
      list: [
          "1. Sầu lẻ bóng 2",
          "2. Ai nhớ chăng ai",
          "3. Hẹn ho",
          "4. Sao chưa thấy hồi âm",
          "5. Xót xa",
          "6. Mưa qua phố vắng",
          "7. Đường xưa lối cu",
          "8. Nhật ký đời tôi",
      ]
  },
  {
      id: 13,
      name: "Tiễn đưa",
      kind: "383",
      singer: "Vũ Khánh",
      pic: "TK.png",
      rot: 78,
      caretory: "New LP",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      price: 1200000,
      list: [
          "01. Cô Láng Giềng",
          "02. Tiễn Đưa",
          "03. Lá Đổ Muôn Chiều",
          "04. Anh Đến Thăm Em Một Chiều Mưa",
          "05. Anh Biết Em Đi Chẳng Trở Ve",
          "06. Áo Lụa Hà Đông",
          "07. Bài Không Tên Cuối Cùng",
          "08. Sang Ngang",
          "09. Tình Khúc Buồn",
      ]
  },
  {
      id: 14,
      name: "Đĩa than Tuyệt Phẩm Song Ca",
      singe: "Nhiều ca sĩ",
      pic: "Song ca.png",
      kind: "383",
      rot: 78,
      caretory: "New LP",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      price: 1200000,
      list: [
          "1A. La Dieu Bong",
          "2A. Mai Lo Hai Minh Xa Nhau",
          "3A. Sau Tim Thiep Hong",
          "4A. Nho Nguoi Yeu",
          "5A. Mat Nhau Roi",
          "1B. Noi Lai Tinh Xua",
          "2B. Doi Nga Chia Ly",
          "3B. Ve Dau Mai Toc Nguoi Thuong",
          "4B. Dung Noi Xa Nhau",
          "5B. Can Nha Mau Tim",
      ]
  },
  {
      id: 15,
      name: "Tuổi Đá Buồn",
      pic: "Tuổi đá buồn.png",
      kind: "383",
      singe: "Nhiều ca sĩ",
      rot: 33,
      caretory: "New LP",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      price: 1200000,
      list: [
          "1. Tôi ơi đừng tuyệt vọng",
          "3. Mưa hồng",
          "4. Như cánh vạc bay",
          "5. Cuối cùng cho một tình yêu",
          "6. Tuổi đá buồn",
          "7. Phôi pha",
          "8. Chiều một mình qua phố",
          "9. Cát bụi tình xa",
      ]
  },
  {
      id: 16,
      name: "Bướm Trắng",
      kind: "Bolero",
      singer: "Tuấn Vũ",
      pic: "TN.png",
      rot: 45,
      caretory: "Old 90s",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      price: 1200000,
      list: [
          "1A. LK Em là tất cả & Hai vì sao lạc",
          "2A. Nhớ người yêu",
          "3A. LK Sầu lẻ bóng & Đôi bóng & Lẻ bóng",
          "4A. Thói đời",
          "5A. Mùa xuân lá khô",
          "1B. LK Tàu đêm năm cũ & Đò chiều",
          "2B. Bướm trắng",
          "3B. Kể chuyện trong đêm",
          "4B. Thôi",
          "5B. LK Rừng lá thay chưa & Xót xa",
      ]
  }, 
  {
      id: 17,
      name: " Mưa nửa đêm",
      singer: "Vũ Khanh",
      kind: "Bolero",
      pic: "TK.png",
      rot: 33,
      caretory: "Old 90s",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      price: 1200000,
      list: [
          "1A. TAU DEM NAM CU",
          "2A. THOI DOI",
          "3A. NUA DEM NGOAI PHUONG",
          "4A. CHIEU CUOI TUAN",
          "5A. CHUYEN CHUNG MINH",
          "1B. HAI LOI MONG",
          "2B. AI CHO TOI TINH YEU",
          "3B. MUA NUA DEM",
          "4B. BUON TRONG KY NIEM",
          "5B. LIEN KHUC TRUC PHUONG",
      ]
  },
  {
      id: 18,
      name: "Phố Buồn",
      singer: "Thanh Huyền",
      pic: "Phố buồn.png",
      kind: "Bolero",
      rot: 33,
      caretory: "New LP",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      price: 1200000,
      list: [
          "1. Nửa đêm ngoài phố",
          "2. Đêm tàn bến Ngự",
          "3. Một chuyến bay đêm",
          "4. Tiếng xưa",
          "5. Phố buồn",
          "6. Chuyện chúng mình",
          "7. Kiếp cầm ca",
          "8. Hãy trả lời em",
          "9. Đêm tâm sự - Hai lối mộng",
          "10. Đèn khuya",
      ]
  },
  {
      id: 19,
      name: "Tình vẫn còn xanh",
      pic: "Thanh Hà.png",
      singer: "Thanh Hà",
      kind: "Bolero",
      rot: 33,
      caretory: "New 100%",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      price: 970000,
      list: [
          "1. Tình Xanh ( sáng tác Trần Quảng Nam)",
          "2. Một Đời Tan Vỡ",
          "3. Mưa Trên Biển Vắng ",
          "4. Lạnh Trọn Đêm Mưa ",
          "5. Chỉ Có Em ",
          "6. Sa Mạc Tình Yêu ",
          "7. Tôi Với Trời Bơ Vơ ",
          "8. Hỡi Người Tình ",
          "9. Tình Khúc Tháng Sáu ",
      ]
  },
  {
      id: 20,
      name: "Đĩa than Quang Dũng tình ca Phạm Duy",
      singer: "Quang Dũng-Phạm Duy",
      pic: "Song ca.png",
      kind: "Bolero",
      rot: 33,
      caretory: "New 100%",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      price: 850000,
      list: [
          "1. Nghin Trung Xa Cach",
          "2. Duong Em Di",
          "3. Chuyen Tinh Buon",
          "4. Roi Day Anh Se Dua Em Ve Nha",
          "5. Cay Dan Bo Quen",
          "6. Hen Ho",
          "7. Con Gi Nua Dau",
          "8. Ky Niem",
      ]
  },
  {
      id: 21,
      name: "Cõi đêm",
      kind: "Bolero",
      singer: "Quang Lê",
      pic: "Cõi đem.png",
      rot: 33,
      caretory: "New 100%",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      price: 1200000,
      list: [
          "1. Cõi đêm ",
          "2. Hạ buồn ",
          "3. Sầu tím thiệp hồng (hát với Lệ Quyên) ",
          "4. Hai lối mộng ",
          "5. Về đâu mái tóc người thương ",
          "6. Không phải tại chúng mình (hát với Hà My)",
          "7. Được tin em lấy chồng ",
          "8. Huyền thoại chiều mưa", 
      ]
  },
  {
      id: 22,
      name: "Thuyền và Biển",
      singe: "Nhiều ca sĩ",
      pic: "Phố nhớ.png",
      kind: "Bolero",
      rot: 33,
      caretory: "New LP",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      price: 1200000,
      list: [
          "1A. THUYEN VA BIEN",
          "2A. XIN CON GOI TEN NHAU",
          "3A. CON MUA HA",
          "4A. RONG REU",
          "5A. GIET NGUOI TRONG MONG",
          "1B. EM DEN THAM ANH DEM 30",
          "2B. GUI NGUOI EM GAI",
          "3B. PHUONG HONG",
          "4B. BIEN NOI NHO VA EM",
          "5B. GIOT NANG BEN THEM",
      ]
  },
  {
      id: 23,
      name: "Moby Play",
      singer: "Moby",
      pic: "Moby.png",
      kind: "Blues",
      rot: 45,
      caretory: "Old 90s",
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, illo quo dolor rem architecto eveniet sunt ad at,",
      price: 3200000,
      list: [
          "1. Honey",
          "2. Find my baby",
          "3. Run on",
          "4. Body rock",
          "5. South side"
      ]
  }
]
console.log(product);
// người dùng
let Nd= [
  {
      name: "Nguyễn Nhật Hoàng",
      user_name: "Hoang",
      phone: "555986",
      email: "Hoang@gmail.com",
      pass: "060352",
      sex: "nam",
      date: "03/06/2000",
      adress:"01, Dai An",
      admin: true, 
  },
  {
      name: "Nguyễn Hien",
      user_name: "Hoang",
      phone: "555236",
      email: "Hien@gmail.com",
      pass: "101020",
      sex: "nu",
      date: "05/06/2000",
      adress:"02, Dai An",
      admin: false, 
  },
  {
      name: "Thành Đỗ",
      user_name: "JK",
      phone: "555302",
      email: "Thanh@gmail.com",
      pass: "130620",
      sex: "nam",
      date: "03/06/1994",
      adress:"01, Phuc kien",
      admin: false, 
  },
  {
      name: "Đỗ Hải",
      user_name: "Hg",
      phone: "555222",
      email: "Hg@gmail.com",
      pass: "iloveyou",
      sex: "nam",
      date: "03/08/2000",
      adress:"01, Dai An",
      admin: false, 
  },
  {
      name: "Nguyễn Sơn",
      user_name: "Songoku",
      phone: "555963",
      email: "Songoku@gmail.com",
      pass: "1023202",
      sex: "nam",
      date: "12/03/2000",
      adress:"133, Dai An",
      admin: false, 
  },

];
console.log(Nd);